
server:
    port: 8080
    address: 127.0.0.1

spring:
    # DATASOURCE
    datasource:
        driverClass: com.mysql.jdbc.Driver
        url: jdbc:mysql://ddssst.cn:3306/test
        username: test
        password: 975965
mybatis:
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
